In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sns.set(rc={'figure.figsize': (10, 5)}, font_scale=1.5)

df = pd.read_csv('/content/drive/MyDrive/ECH_2019.csv')

# df = pd.read_csv('ECH_2019.csv')

In [3]:
no_data = {0: 'No hay dato', '0': 'No hay dato'}

mask = df.columns.difference(['edad',
                              'sueldo',
                              'hijos en hogar',
                              'hijos en otro hogar',
                              'hijos en el extranjero',
                              'suma_hijos',
                              'barrio'])

df[mask] = df[mask].replace(no_data)

In [4]:
df['rango_edades'] = pd.qcut(df['edad'], q=10)

df['rango_edades'].value_counts()

(8.0, 16.0]      11803
(39.0, 47.0]     11347
(63.0, 73.0]     10988
(-0.001, 8.0]    10918
(55.0, 63.0]     10848
(47.0, 55.0]     10834
(16.0, 23.0]     10657
(31.0, 39.0]     10484
(23.0, 31.0]     10116
(73.0, 98.0]      9876
Name: rango_edades, dtype: int64

### AJUSTANDO DATOS PARA ENTRENAR EL MODELO

Seleccionamos personas con edad suficiente para trabajar

In [5]:
df = df[~df['estado_laboral'].str.contains('Menores de 14 años')]

In [6]:
df['estado_laboral'].value_counts()

Ocupados                                      49036
Inactivo: jubilado                            16025
Inactivo: estudiante                           8216
Inactivo: realiza los quehaceres del hogar     5936
Inactivo: pensionista                          4438
Desocupados propiamente dichos                 3409
Inactivo: otro                                 1291
Desocupados buscan trabajo por primera vez      787
Inactivo: rentista                              414
Desocupados en seguro de paro                   255
Name: estado_laboral, dtype: int64

In [7]:
df.groupby(by='estado_laboral').mean()

id_hogar  ...  suma_hijos
estado_laboral                                            ...            
Desocupados buscan trabajo por primera vez  2.019029e+09  ...    0.174079
Desocupados en seguro de paro               2.019030e+09  ...    0.733333
Desocupados propiamente dichos              2.019029e+09  ...    0.925785
Inactivo: estudiante                        2.019029e+09  ...    0.037610
Inactivo: jubilado                          2.019029e+09  ...    1.212917
Inactivo: otro                              2.019029e+09  ...    0.563129
Inactivo: pensionista                       2.019029e+09  ...    2.160207
Inactivo: realiza los quehaceres del hogar  2.019029e+09  ...    2.266678
Inactivo: rentista                          2.019029e+09  ...    1.514493
Ocupados                                    2.019029e+09  ...    0.795660

[10 rows x 9 columns]

In [8]:
quantil_99 = df["sueldo"].quantile(0.99)
print(quantil_99)

df = df[df["sueldo"] < quantil_99]

quartil_1 = df["sueldo"].quantile(0.25)
quartil_3 = df["sueldo"].quantile(0.75)

iqr = quartil_3 - quartil_1

df = df[df["sueldo"] < quartil_3 + 1.5 * iqr]

df = df[df["sueldo"] > quartil_1 - 1.5 * iqr]

84000.0


In [9]:
df['rango_sueldos'] = pd.qcut(df['sueldo'], q=10, duplicates='drop').cat.codes

df['rango_edades'] = pd.qcut(df['edad'], q=10).cat.codes

In [10]:
df = df[[
    'sexo', 
    'edad', 
    'ascendencia', 
    'parentesco', 
    'estado_laboral', 
    'busca_otro_trabajo',
    'actividad',
    'asistencia alguna vez a enseñanza',
    'edu preescolar',
    'edu primaria',
    'edu media',
    'edu técnica',
    'edu univ o simil',
    'edu terciario no uni',
    'edu posgrado',
    'edu mag prof',
    'barrio',
    'estado_civil',
    'suma_hijos',
    'leer_escribir',
    'rango_sueldos',
    'rango_edades',
    'region',
    'vivienda',
    'estrato'
    ]]


In [11]:
df = df.reset_index(drop=True)

df.head(2)

sexo  edad  ...                                           vivienda     estrato
0  Mujer  76.0  ...  Propietario de la vivienda y el terreno y ya l...  Costa Este
1  Mujer  22.0  ...  Propietario de la vivienda y el terreno y ya l...  Costa Este

[2 rows x 25 columns]

In [12]:
df['rango_sueldos'].value_counts()

0    59982
1     9344
3     8546
2     7674
Name: rango_sueldos, dtype: int64

### DEFINIMOS LAS VARIABLES DEPENDIENTES E INDEPENDIENTES

In [13]:
# Feautures
X = df.drop('rango_sueldos', axis=1).to_numpy()
y = df['rango_sueldos']

print('X shape', X.shape, '\nY shape', y.shape)

X shape (85546, 24) 
Y shape (85546,)


In [14]:
y.unique()

array([0, 1, 3, 2], dtype=int8)

In [15]:
from sklearn.preprocessing import OneHotEncoder

one_hot = OneHotEncoder()

X = one_hot.fit_transform(X)

In [16]:
from sklearn.preprocessing import Normalizer

normalizer = Normalizer()

X = normalizer.fit_transform(X)

In [17]:
X.shape

(85546, 660)

## Dejamos una fila afuera para testear el modelo más adelante

In [18]:
test_sample = X[0]
test_result = y[0]

X = X[1:]
y = y[1:]

### Dividimos los datos en un 30% de test y 70% de entrenamiento

In [19]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42) 

In [20]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(59881, 660) (59881,)
(25664, 660) (25664,)


# DEFINIMOS ALGORITMO DE REGRESIÓN LOGISTICA

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

logistic_reg = LogisticRegression(multi_class='multinomial',max_iter=20000)

In [22]:
#Definicion de Hyperparámetros
param_grid = {'solver':['lbfgs', 'saga'],
              'penalty': ['l1', 'l2'], 
              'C':[10, 1.0, 0.1]}

# RANDOM SEARCH

In [23]:
from sklearn.model_selection import RandomizedSearchCV

#Aplicamos la búsqueda al modelo
model = RandomizedSearchCV(logistic_reg, param_grid,n_iter=100, random_state=0, cv=5,scoring='accuracy',verbose=20)

In [24]:
model.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5; 1/12] START C=10, penalty=l1, solver=lbfgs.............................
[CV 1/5; 1/12] END C=10, penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 2/5; 1/12] START C=10, penalty=l1, solver=lbfgs.............................
[CV 2/5; 1/12] END C=10, penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 3/5; 1/12] START C=10, penalty=l1, solver=lbfgs.............................
[CV 3/5; 1/12] END C=10, penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 4/5; 1/12] START C=10, penalty=l1, solver=lbfgs.............................
[CV 4/5; 1/12] END C=10, penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 5/5; 1/12] START C=10, penalty=l1, solver=lbfgs.............................
[CV 5/5; 1/12] END C=10, penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 1/5; 2/12] START C=10, penalty=l1, solver=saga..............................


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_search.py:296: UserWarning: The total space of parameters 12 is smaller than n_iter=100. Running 12 iterations. For exhaustive searches, use GridSearchCV.
  UserWarning,


[CV 1/5; 2/12] END C=10, penalty=l1, solver=saga;, score=0.772 total time= 3.5min
[CV 2/5; 2/12] START C=10, penalty=l1, solver=saga..............................
[CV 2/5; 2/12] END C=10, penalty=l1, solver=saga;, score=0.766 total time= 3.1min
[CV 3/5; 2/12] START C=10, penalty=l1, solver=saga..............................
[CV 3/5; 2/12] END C=10, penalty=l1, solver=saga;, score=0.770 total time= 5.5min
[CV 4/5; 2/12] START C=10, penalty=l1, solver=saga..............................
[CV 4/5; 2/12] END C=10, penalty=l1, solver=saga;, score=0.767 total time= 7.7min
[CV 5/5; 2/12] START C=10, penalty=l1, solver=saga..............................
[CV 5/5; 2/12] END C=10, penalty=l1, solver=saga;, score=0.765 total time= 4.2min
[CV 1/5; 3/12] START C=10, penalty=l2, solver=lbfgs.............................
[CV 1/5; 3/12] END C=10, penalty=l2, solver=lbfgs;, score=0.773 total time=  27.7s
[CV 2/5; 3/12] START C=10, penalty=l2, solver=lbfgs.............................
[CV 2/5; 3/12] END C=

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
15 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver

RandomizedSearchCV(cv=5,
                   estimator=LogisticRegression(max_iter=20000,
                                                multi_class='multinomial'),
                   n_iter=100,
                   param_distributions={'C': [10, 1.0, 0.1],
                                        'penalty': ['l1', 'l2'],
                                        'solver': ['lbfgs', 'saga']},
                   random_state=0, scoring='accuracy', verbose=20)

In [25]:
print("Mejores parametros: "+str(model.best_params_))
print("Mejor Score: "+str(model.best_score_)+'\n')

Mejores parametros: {'solver': 'lbfgs', 'penalty': 'l2', 'C': 10}
Mejor Score: 0.7684072634428635



In [26]:
# Prediccion
prediction = model.predict(X_test)

In [28]:
from sklearn.metrics import confusion_matrix

# Matriz de Confusion
cm = confusion_matrix(y_test,prediction)
print("Matriz de confusión:")
print(cm)

Matriz de confusión:
[[17162   456   147   340]
 [ 1386   744   296   260]
 [  760   394   476   670]
 [  645   143   314  1471]]


# GRID SEARCH CV

In [ ]:
from sklearn.model_selection import GridSearchCV

#Grid Search con hyperparámetros
model = GridSearchCV(logistic_reg, param_grid=param_grid, cv=5,scoring='accuracy',verbose=20)

In [ ]:
model.fit(X_train, y_train)

In [ ]:
model

In [ ]:
print("Mejores parametros: "+str(model.best_params_))
print("Mejor Score: "+str(model.best_score_)+'\n')

In [ ]:
print('Promedio de cross_validation ', round(scores.mean(),2))
print('Score en test ', round(logistic_reg.score(X_test, y_test),2))
print('Score en train ', round(logistic_reg.score(X_train, y_train),2))

In [ ]:
from sklearn.metrics import accuracy_score

#Prediccion en Train y Test
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

#Calculo el accuracy en Train y Test
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print('Aciertos sobre train:', round(train_accuracy, 2))
print('Exactitud sobre test:', round(test_accuracy, 2))

### APLICAMOS PREDICCIÓN SOBRE EL MODELO

In [ ]:
print(model.predict(test_sample))

print(test_result)

Determinamos la probabilidad de la predicción

In [ ]:
probabilidades_prediccion = model.predict_proba(test_sample)
probabilidades_prediccion

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_test_pred)

print("Matriz de confusión:")
print(cm)

# REPETIMOS EL EJERCICIO CON EL MODELO DE RANDOM FOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(100)

random_forest.fit(X_train, y_train)

In [ ]:
scores = cross_val_score(random_forest, X, y, cv=5)

scores

In [ ]:
print('Promedio de cross_validation ', round(scores.mean(),2))
print('Score en test ', round(logistic_reg.score(X_test, y_test),2))
print('Score en train ', round(logistic_reg.score(X_train, y_train),2))

In [ ]:
predictions = logistic_reg.predict(X_test)

confusion_matrix(y_test, predictions)

In [ ]:
#Prediccion en Train
y_train_pred = random_forest.predict(X_train)

#Prediccion en Test
y_test_pred = random_forest.predict(X_test)

#Calculo el accuracy en Train
train_accuracy = accuracy_score(y_train, y_train_pred)

#Calculo el accuracy en Test
test_accuracy = accuracy_score(y_test, y_test_pred)

print('Aciertos sobre entrenamiento:', round(train_accuracy, 2))
print('Aciertos sobre evaluación:', round(test_accuracy, 2))

In [ ]:
print(random_forest.predict(test_sample))
print(test_result)

In [ ]:
probabilidades_prediccion = random_forest.predict_proba(test_sample)
probabilidades_prediccion

# REPETIMOS EL EJERCICIO CON EL MODELO DE K NEAREST NEIGHBOURS

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knearest_model = KNeighborsClassifier(n_neighbors=4)

knearest_model.fit(X_train, y_train)

In [ ]:
scores = cross_val_score(knearest_model, X, y, cv=5)

scores           

In [ ]:
print('Promedio de cross_validation ', round(scores.mean(),2))
print('Score en test ', round(knearest_model.score(X_test, y_test),2))
print('Score en train ', round(knearest_model.score(X_train, y_train),2))

In [ ]:
predictions = knearest_model.predict(X_test)

confusion_matrix(y_test, predictions)

In [ ]:
#Prediccion en Train
y_train_pred = knearest_model.predict(X_train)

#Prediccion en Test
y_test_pred = knearest_model.predict(X_test)

#Calculo el accuracy en Train
train_accuracy = accuracy_score(y_train, y_train_pred)

#Calculo el accuracy en Test
test_accuracy = accuracy_score(y_test, y_test_pred)

print('Aciertos sobre entrenamiento:', round(train_accuracy, 2))
print('Aciertos sobre evaluación:', round(test_accuracy, 2))

In [ ]:
print(knearest_model.predict(test_sample))
print(test_result)

In [ ]:
probabilidades_prediccion = knearest_model.predict_proba(test_sample)
probabilidades_prediccion

# Columna que diga por arriba de la media de hombres o no

# Cómo determino si afecta o no