In [1]:
import pandas as pd

moms = pd.read_csv('moms.csv', usecols=['edad', 'ascendencia',
       'estado_laboral', 'sueldo', 'busca_otro_trabajo', 'actividad',
       'asistencia alguna vez a enseñanza', 'edu preescolar', 'edu primaria',
       'edu media', 'edu técnica', 'edu univ o simil', 'edu terciario no uni',
       'edu posgrado', 'edu mag prof', 'hijos'])

In [2]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

# Feautures
X = moms['sueldo']
X = le.fit_transform(X).reshape(-1, 1)

y = moms['hijos'].to_numpy()

print('X shape', X.shape, '\nY shape', y.shape)

X shape (10087, 1) 
Y shape (10087,)


In [3]:
# Split #30% test, 70% para train
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42) 

In [4]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(7060, 1) (7060,)
(3027, 1) (3027,)


In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

logistic_regression = LogisticRegression()

clf = LogisticRegression().fit(X_train, y_train)

scores = cross_val_score(clf, X, y, cv=10)

scores

/Users/anicolon/pyenv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anicolon/pyenv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regres

array([0.42517344, 0.39544103, 0.39544103, 0.39544103, 0.39643211,
       0.42616452, 0.39444995, 0.39186508, 0.39484127, 0.39484127])

In [6]:
clf.score(X_test, y_test)

0.39610175090849026

In [7]:
clf.score(X_train, y_train)

0.39291784702549576

In [8]:
# from sklearn.model_selection import KFold

# kf = KFold(n_splits=10, shuffle=True)

# for train, test in kf.split(X):
#     print("%s %s" % (train, test))

[    0     1     2 ... 10084 10085 10086] [    6    14    15 ... 10071 10072 10078]
[    0     1     2 ... 10084 10085 10086] [    4    16    18 ... 10045 10061 10062]
[    0     1     2 ... 10084 10085 10086] [    8    25    30 ... 10017 10064 10080]
[    0     2     3 ... 10084 10085 10086] [    1    12    13 ... 10077 10081 10083]
[    0     1     2 ... 10083 10084 10085] [   11    20    28 ... 10057 10063 10086]
[    0     1     2 ... 10084 10085 10086] [   22    24    31 ... 10051 10059 10074]
[    1     2     4 ... 10084 10085 10086] [    0     3     7 ... 10048 10070 10073]
[    0     1     2 ... 10084 10085 10086] [   10    19    26 ... 10047 10052 10054]
[    0     1     3 ... 10083 10085 10086] [    2     5    17 ... 10068 10082 10084]
[    0     1     2 ... 10083 10084 10086] [    9    21    45 ... 10075 10079 10085]
