In [1]:
import pandas as pd

moms = pd.read_csv('moms.csv', usecols=['edad', 'ascendencia',
       'estado_laboral', 'sueldo', 'busca_otro_trabajo', 'actividad',
       'asistencia alguna vez a enseñanza', 'edu preescolar', 'edu primaria',
       'edu media', 'edu técnica', 'edu univ o simil', 'edu terciario no uni',
       'edu posgrado', 'edu mag prof', 'hijos'])

In [2]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

# Feautures
X = moms['sueldo']
X = le.fit_transform(X).reshape(-1, 1)

y = moms['hijos'].to_numpy()

print('X shape', X.shape, '\nY shape', y.shape)

X shape (10087, 1) 
Y shape (10087,)


In [3]:
# Split #30% test, 70% para train
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42) 

In [4]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(7060, 1) (7060,)
(3027, 1) (3027,)


In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

logistic_regression = LogisticRegression(max_iter=20000)

clf = logistic_regression.fit(X_train, y_train)

scores = cross_val_score(clf, X, y, cv=10)

scores

array([0.39444995, 0.39147671, 0.33994054, 0.40832507, 0.39643211,
       0.39544103, 0.40634291, 0.38492063, 0.36805556, 0.36805556])

In [6]:
clf.score(X_test, y_test)

0.39544103072348863

In [7]:
clf.score(X_train, y_train)

0.39277620396600565

In [8]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=10, shuffle=True)

for train, test in kf.split(X):
    print("%s %s" % (train, test))

[    0     1     2 ... 10084 10085 10086] [    7    10    18 ... 10073 10076 10077]
[    0     1     2 ... 10084 10085 10086] [   24    29    41 ... 10038 10061 10070]
[    0     1     2 ... 10084 10085 10086] [    4    13    35 ... 10055 10082 10083]
[    0     1     2 ... 10083 10084 10086] [   23    27    38 ... 10069 10075 10085]
[    0     2     3 ... 10083 10085 10086] [    1    16    17 ... 10079 10080 10084]
[    0     1     2 ... 10083 10084 10085] [   11    20    21 ... 10060 10081 10086]
[    0     1     2 ... 10084 10085 10086] [   14    34    69 ... 10052 10074 10078]
[    0     1     2 ... 10084 10085 10086] [    3     5     6 ... 10051 10063 10072]
[    1     2     3 ... 10084 10085 10086] [    0    12    15 ... 10048 10064 10066]
[    0     1     3 ... 10084 10085 10086] [    2     8    30 ... 10034 10065 10067]
